version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@angular/cli"
    versions:
    - 11.0.5
    - 11.1.2
    - 11.2.2
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.4
  - dependency-name: karma
    versions:
    - 6.0.3
