language: node_js
node_js: stable

sudo: required

addons:
  chrome: stable

# Use headless Chrome for Travis
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

before_script:
  - npm install
  - npm run build

script:
  - npm test
