dist: trusty
language: node_js
node_js: lts/*

sudo: required
  
addons:
  chrome: stable

# 1. Use headless Chrome for Travis
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - npm install

before_script:
  - npm run build

script:
  - npm run lint
  - npm run test
