language: node_js
node_js: stable

sudo: required

addons:
  chrome: stable

env:
  - NG_CLI_ANALYTICS=ci

# 1. Use headless Chrome for Travis
# 2. Install greenkeep-lockfile
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g greenkeeper-lockfile

install: npm install

before_script:
  - greenkeeper-lockfile-update
  - npm run build

script:
  - npm run lint
  - npm run test

after_script:
  - greenkeeper-lockfile-upload
