name: ci
on: [push,pull_request]
jobs:
  test:
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node:
          - 'lts/*'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: GabrielBB/xvfb-action@v1
         with:
            run: |
              export CHROME_BIN=chromium-browser
              export DISPLAY=:99
              npm install
              npm run build
              npm run lint
              npm run test
  
